// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemFre.Data;

#nullable disable

namespace SemFre.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904130614_AddFriendInviteCode")]
    partial class AddFriendInviteCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("SemFre.Models.FreeTime", b =>
                {
                    b.Property<int>("FreeTimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FreeTimeID");

                    b.HasIndex("UserID");

                    b.ToTable("FreeTimes");
                });

            modelBuilder.Entity("SemFre.Models.FriendPair", b =>
                {
                    b.Property<int>("Friend1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Friend2ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EstablishedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Friend1ID", "Friend2ID");

                    b.HasIndex("Friend2ID");

                    b.ToTable("FriendPairs", t =>
                        {
                            t.HasCheckConstraint("CK_FriendPair_Order", "Friend1ID < Friend2ID");
                        });
                });

            modelBuilder.Entity("SemFre.Models.FriendSuggestion", b =>
                {
                    b.Property<int>("SuggesterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestedID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SuggestedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SuggesterID", "SuggestedID");

                    b.HasIndex("SuggestedID");

                    b.ToTable("FriendSuggestions", t =>
                        {
                            t.HasCheckConstraint("CK_FriendSuggestion_NotSelf", "SuggesterID != SuggestedID");
                        });
                });

            modelBuilder.Entity("SemFre.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupID");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SemFre.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SemFre.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SemFre.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendInviteCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FriendInviteCodeGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("FriendInviteCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SemFre.Models.UserDevice", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceID");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("SemFre.Models.FreeTime", b =>
                {
                    b.HasOne("SemFre.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SemFre.Models.FriendPair", b =>
                {
                    b.HasOne("SemFre.Models.User", "Friend1")
                        .WithMany()
                        .HasForeignKey("Friend1ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemFre.Models.User", "Friend2")
                        .WithMany()
                        .HasForeignKey("Friend2ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend1");

                    b.Navigation("Friend2");
                });

            modelBuilder.Entity("SemFre.Models.FriendSuggestion", b =>
                {
                    b.HasOne("SemFre.Models.User", "Suggested")
                        .WithMany()
                        .HasForeignKey("SuggestedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemFre.Models.User", "Suggester")
                        .WithMany()
                        .HasForeignKey("SuggesterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggested");

                    b.Navigation("Suggester");
                });

            modelBuilder.Entity("SemFre.Models.Group", b =>
                {
                    b.HasOne("SemFre.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SemFre.Models.GroupMember", b =>
                {
                    b.HasOne("SemFre.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemFre.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SemFre.Models.UserDevice", b =>
                {
                    b.HasOne("SemFre.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SemFre.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
